- name: create django superuser
  django_manage:
    command: "createsuperuser --noinput --username=admin --email=support@typeamachines.com"
    virtualenv: "{{pod_virtualenv}}"
    app_path: "{{pod_home}}"
- name: reload systemd
  command: systemctl daemon-reload
- name: restart pod
  service: name=pod-web state=restarted enabled=yes
