---
- hosts: default
  tasks:
    - name: install deps
      apt: name={{item}} state=present
      with_items:
        - python3-pip
        - python3-venv
        - rabbitmq-server
        - avahi-daemon
        - sudo
        - unattended-upgrades
      become: true
    - name: configure sudo
      copy:
        dest: /etc/sudoers.d/nopass
        content: '%sudo ALL=(ALL) NOPASSWD: ALL'
        mode: 'u=r,g=r,o-rwx'
        validate: 'visudo -cf %s'
      become: true
