---
- hosts: default
  tasks:
    - name: install deps
      apt: name={{item}} state=present
      with_items:
        - python3-pip
        - python3-venv
        - rabbitmq-server
        - avahi-daemon
      become: true
