---
- hosts: default
  become: true
  vars:
    - pod_package: git+ssh://git@bitbucket.org/typeamachines/pod.git
    - pod_package_dir: /dev/null
    - pod_prerelase: false
  vars_prompt:
    - name: user_typea_pass
      prompt: "new password for user 'typea'"
      confirm: true
      private: true
      encrypt: 'sha512_crypt'
  roles:
    - base
    - pod
