- name: create sqlite db
  # Create an empty db with the proper permissions.
  # We use `copy` instead of `file` with the `touch` param because we
  # don't want to trigger handlers if the file is already present.
  #
  # This isn't the best location for it, but it's the default for a
  # virtualenv and it's ok for now.
  copy:
    content: ""
    dest: "{{pod_virtualenv}}/lib/python3.4/site-packages/db.sqlite3"
    owner: "{{pod_web_user}}"
    mode: "u=rw,g=r,o-rwx"
