---
  - name: install deps
    apt: name={{item}} state=present
    with_items:
      - python3-pip
      - python3-venv
      - rabbitmq-server
      - avahi-daemon
      - sudo
      - unattended-upgrades
      - git
  - name: configure typea admin user
    user:
      name: typea
      state: present
      groups: sudo
      append: true
      password: "{{user_typea_pass}}"
  - name: configure sudo
    copy:
      dest: /etc/sudoers.d/nopass
      content: '%sudo ALL=(ALL) NOPASSWD: ALL'
      mode: 'u=r,g=r,o-rwx'
      validate: 'visudo -cf %s'
  - name: disable root ssh access
    lineinfile:
      dest: /etc/ssh/sshd_config
      regexp: "^PermitRootLogin"
      line: "PermitRootLogin no"
      state: present
      validate: 'echo "checking %s"; sshd -t'
    notify: [reload sshd]
  - name: transfer user certificate authority public key
    copy:
      src: typea-user-ca.pub
      dest: /etc/ssh/typea-user-ca.pub
  - name: authorize user certificate authorize public key
    lineinfile:
      dest: /etc/ssh/sshd_config
      regexp: '^TrustedUserCAKeys '
      line: 'TrustedUserCAKeys /etc/ssh/typea-user-ca.pub'
      state: present
    notify: [reload sshd]
