# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-22 20:40
from __future__ import unicode_literals

from django.db import migrations


def init_admin_user(apps, schema_editor):
    User = apps.get_model('auth', 'User')
    password = 'pbkdf2_sha256$24000$zB0UdKqViWEk$3+9QFz47cTjbZztbTrzJBqJlei0UHZlPIxteCpLAd4E='
    u = User.objects.create(
        username='admin',
        email='support@typeamachines.com',
        password=password,
        is_staff=True,
        is_superuser=True,
    )
    u.save()


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(init_admin_user),
    ]
