# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-28 23:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('printers', '0001_initial'),
        ('files', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrintLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('host', models.CharField(max_length=64)),
                ('port', models.IntegerField()),
                ('filename', models.CharField(max_length=256)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('event', models.CharField(choices=[('started', 'PrintStarted'), ('paused', 'PrintPaused'), ('resumed', 'PrintResumed'), ('cancelled', 'PrintCancelled'), ('failed', 'PrintFailed'), ('done', 'PrintDone')], max_length=32)),
                ('orig_data', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='PrintRun',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('printer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='printers.Printer')),
                ('printfile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='files.PrintFile')),
            ],
        ),
        migrations.AddField(
            model_name='printlog',
            name='printrun',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='files.PrintRun'),
        ),
    ]
