# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-05-11 23:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0002_printrun_printlog'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='printfile',
            options={'get_latest_by': 'createdAt', 'ordering': ['-createdAt']},
        ),
        migrations.AlterModelOptions(
            name='printlog',
            options={'get_latest_by': 'timestamp', 'ordering': ['-timestamp']},
        ),
    ]
